openapi: 3.0.3
info:
  title: system
  version: '1.0'
  description: System Docs Here
paths:
  /infoPush:
    get:
      summary: Show Information Notices
      tags:
        - system
      responses:
        '200':
          $ref: ../responses/system/InfoPushListResponse.yaml
      operationId: getInfoPush
      description: |-
        IPS (Info Push System) is a system for VRChat to push out dynamic information to the client. This is primarily used by the Quick-Menu info banners, but can also be used to e.g. alert you to update your game to the latest version.

        `include` is used to query what Information Pushes should be included in the response. If include is missing or empty, then no notices will normally be returned. This is an "any of" search.

        `require` is used to limit what Information Pushes should be included in the response. This is usually used in combination with `include`, and is an "all of" search.
      parameters:
        - $ref: ../parameters.yaml#/require
        - $ref: ../parameters.yaml#/include
      x-badges:
        - color: gold
          label: 'Status: Early Access (Still Under Development)'
  /health:
    get:
      summary: Check API Health
      tags:
        - system
      operationId: getHealth
      description: |-
        ~~Gets the overall health status, the server name, and the current build version tag of the API.~~

        **DEPRECATED:** VRChat has suddenly restricted this endpoint for unknown reasons, and now always return 401 Unauthorized.
      security: []
      responses:
        '200':
          $ref: ../responses/system/APIHealthResponse.yaml
      deprecated: true
  /config:
    get:
      summary: Fetch API Config
      tags:
        - system
      responses:
        '200':
          $ref: ../responses/system/APIConfigResponse.yaml
      operationId: getConfig
      description: |-
        API config contains configuration that the clients needs to work properly.

        Currently the most important value here is `clientApiKey` which is used for all other API endpoints.
      security: []
  /visits:
    get:
      summary: Current Online Users
      tags:
        - system
      responses:
        '200':
          $ref: ../responses/system/CurrentOnlineUsersResponse.yaml
      operationId: getCurrentOnlineUsers
      security: []
      description: |-
        Returns the current number of online users.

        **NOTE:** The response type is not a JSON object, but a simple JSON integer.
  /time:
    get:
      summary: Current System Time
      tags:
        - system
      responses:
        '200':
          $ref: ../responses/system/SystemTimeResponse.yaml
      operationId: getSystemTime
      description: |-
        Returns the current time of the API server.

        **NOTE:** The response type is not a JSON object, but a simple JSON string.
      security: []
  /js/app.js:
    get:
      summary: Download JavaScript
      tags:
        - system
      responses:
        '200':
          description: '**Note:** VRChat uses 302 Redirect to Cloudfront. The implementing library **must** support and follow redirects natively.'
          content:
            application/javascript:
              schema:
                type: string
        '400':
          $ref: ../responses/system/DownloadSourceCodeAccessError.yaml
      operationId: getJavaScript
      description: Fetches the JavaScript code to the frontend React website.
      parameters:
        - $ref: ../parameters.yaml#/variant
        - $ref: ../parameters.yaml#/branch
  /css/app.css:
    get:
      summary: Download CSS
      tags:
        - system
      responses:
        '200':
          description: '**Note:** VRChat uses 302 Redirect to Cloudfront. The implementing library **must** support and follow redirects natively.'
          content:
            text/css:
              schema:
                type: string
        '400':
          $ref: ../responses/system/DownloadSourceCodeAccessError.yaml
      operationId: getCSS
      description: Fetches the CSS code to the frontend React website.
      parameters:
        - $ref: ../parameters.yaml#/variant
        - $ref: ../parameters.yaml#/branch
tags:
  $ref: ../tags.yaml
